Repository AY2021S1-CS2113-T13-1/tp, pull requests merged in 2020-11, with the labels that each got.

#174 Update documents, test kramdown as seen in AB-3
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/diagrams/github-icon.png
  docs/team/brandon.md
  docs/team/junxiang.md
  docs/team/nazrylLim.md
  docs/team/prachi2023.md
  docs/team/r-ramana.md
Labels: priority.High

#176 Update user guide for ViewNote
  docs/UserGuide.md
Labels: severity.VeryLow, type.Bug

#177 Prachi branch pin unpin phrasing
  docs/UserGuide.md
  src/main/java/seedu/notus/command/PinCommand.java
  src/main/java/seedu/notus/data/notebook/Note.java
Labels: severity.VeryLow, type.Bug

#179 Userguide and addNote bugs
  docs/UserGuide.md
  docs/screenshots/addNote.png
  src/main/java/seedu/notus/command/AddNoteCommand.java
  src/main/java/seedu/notus/command/HelpCommand.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/CommandMessage.java
  src/main/java/seedu/notus/util/parser/Parser.java
  src/test/java/seedu/notus/command/AddNoteCommandTest.java
  src/test/java/seedu/notus/command/HelpCommandTest.java
Labels: priority.High, type.Bug, type.Story

#180 Userguide and editNote bugs
  docs/UserGuide.md
  docs/screenshots/editNote.png
  src/main/java/seedu/notus/command/EditNoteCommand.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/ui/InterfaceManager.java
  src/main/java/seedu/notus/util/parser/ParseDeleteNoteCommand.java
  src/main/java/seedu/notus/util/parser/ParseEditNoteCommand.java
  src/test/java/seedu/notus/command/AddNoteCommandTest.java
Labels: priority.High, type.Bug, type.Story

#178 Updated DateTime Format issues on User Guide.
  docs/UserGuide.md
Labels: severity.VeryLow, type.Bug

#181 User Guide suggestion fixes
  docs/DeveloperGuide.md
  docs/diagrams/AddNote_Sequence.puml
  docs/diagrams/PinCommand.puml
  docs/diagrams/out/AddNote_Sequence.png
  docs/diagrams/out/PinCommand.png
Labels: severity.VeryLow

#182 Add Note Display & User guide add-on
  docs/UserGuide.md
  docs/diagrams/NotebookObject.puml
  docs/diagrams/out/NotebookObject.png
  docs/screenshots/addNote.png
  docs/screenshots/editNote.png
  src/main/java/seedu/notus/data/notebook/Note.java
  src/main/java/seedu/notus/ui/Formatter.java
Labels: severity.VeryLow, type.Story

#183 Minor error fix in Add note sequence
  docs/diagrams/AddNote_Sequence.puml
  docs/diagrams/out/AddNote_Sequence.png
Labels: severity.VeryLow, type.Task

#184 Included a new doc called Dev Pract
  docs/DeveloperGuide.md
  docs/DevelopmentPractices.md
  docs/UserGuide.md
  docs/index.md
  docs/screenshots/kanban.png
Labels: priority.Medium, type.Task

#189 Refactored Events to have end date
  TagManager.log.2
  TagManager.log.2.lck
  src/main/java/seedu/notus/command/AddEventCommand.java
  src/main/java/seedu/notus/command/EditEventCommand.java
  src/main/java/seedu/notus/data/exception/SystemException.java
  src/main/java/seedu/notus/data/timetable/DailyEvent.java
  src/main/java/seedu/notus/data/timetable/Event.java
  src/main/java/seedu/notus/data/timetable/MonthlyEvent.java
  src/main/java/seedu/notus/data/timetable/RecurringEvent.java
  src/main/java/seedu/notus/data/timetable/WeeklyEvent.java
  src/main/java/seedu/notus/data/timetable/YearlyEvent.java
  src/main/java/seedu/notus/storage/StorageManager.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/CommandMessage.java
  src/main/java/seedu/notus/util/PrefixSyntax.java
  src/main/java/seedu/notus/util/parser/ParseAddEventCommand.java
  src/main/java/seedu/notus/util/parser/ParseEditEventCommand.java
  src/test/java/seedu/notus/command/AddEventCommandTest.java
  src/test/java/seedu/notus/command/RemindCommandTest.java
  src/test/java/seedu/notus/data/timetable/DailyEventTest.java
  src/test/java/seedu/notus/data/timetable/EventTest.java
  src/test/java/seedu/notus/data/timetable/MonthlyEventTest.java
  src/test/java/seedu/notus/data/timetable/TimetableTest.java
  src/test/java/seedu/notus/data/timetable/WeeklyEventTest.java
  src/test/java/seedu/notus/data/timetable/YearlyEventTest.java
Labels: priority.High, type.Enhancement

#191 Added clashing events detection and relevant warning messages
  docs/UserGuide.md
  docs/screenshots/addEvent.png
  src/main/java/seedu/notus/command/AddEventCommand.java
  src/main/java/seedu/notus/command/EditEventCommand.java
  src/main/java/seedu/notus/data/timetable/DailyEvent.java
  src/main/java/seedu/notus/data/timetable/Event.java
  src/main/java/seedu/notus/data/timetable/MonthlyEvent.java
  src/main/java/seedu/notus/data/timetable/RecurringEvent.java
  src/main/java/seedu/notus/data/timetable/Timetable.java
  src/main/java/seedu/notus/data/timetable/WeeklyEvent.java
  src/main/java/seedu/notus/data/timetable/YearlyEvent.java
  src/main/java/seedu/notus/util/CommandMessage.java
  src/main/java/seedu/notus/util/parser/ParseListEventCommand.java
Labels: priority.Medium, type.Enhancement

#192 Fix Storage loading issues
  .gitignore
  data/notes/C++ Standard Libraries.txt
  data/notes/Java OOP.txt
  data/notes/test 2.txt
  data/notes/test1.txt
  src/main/java/seedu/notus/Notus.java
  src/main/java/seedu/notus/command/AddEventCommand.java
  src/main/java/seedu/notus/command/AddNoteCommand.java
  src/main/java/seedu/notus/command/DeleteEventCommand.java
  src/main/java/seedu/notus/command/EditEventCommand.java
  src/main/java/seedu/notus/command/PinCommand.java
  src/main/java/seedu/notus/data/notebook/Note.java
  src/main/java/seedu/notus/storage/StorageManager.java
  src/main/java/seedu/notus/util/PrefixSyntax.java
  src/main/java/seedu/notus/util/parser/ParseAddNoteCommand.java
Labels: priority.High, severity.Medium, type.Bug

#194 create a logging directory
  FindCommandParser.log.1
  FindCommandParser.log.1.lck
  src/main/java/seedu/notus/Notus.java
  src/main/java/seedu/notus/command/FindCommand.java
  src/main/java/seedu/notus/command/HelpCommand.java
  src/main/java/seedu/notus/command/PinCommand.java
  src/main/java/seedu/notus/command/ViewNoteCommand.java
  src/main/java/seedu/notus/data/tag/TagManager.java
  src/main/java/seedu/notus/storage/StorageManager.java
Labels: priority.Low, type.Task

#190 Fixed reminder display and timetable sorting issue
  src/main/java/seedu/notus/data/timetable/Event.java
  src/main/java/seedu/notus/storage/StorageManager.java
Labels: severity.Medium, severity.VeryLow, type.Bug

#195 Brandon branch dev guide & PPP
  docs/DeveloperGuide.md
  docs/diagrams/AddEvent_Sequence.puml
  docs/diagrams/Remind_Sequence.puml
  docs/diagrams/TimetableClass.puml
  docs/diagrams/out/AddEvent_Sequence.png
  docs/diagrams/out/Remind_Sequence.png
  docs/diagrams/out/TimetableClass.png
  docs/team/brandon.md
  src/main/java/seedu/notus/data/exception/SystemException.java
  src/main/java/seedu/notus/data/timetable/Event.java
  src/main/java/seedu/notus/data/timetable/Timetable.java
  src/main/java/seedu/notus/util/CommandMessage.java
Labels: priority.High, type.Task

#197 Updates to Documentation & Test Cases
  docs/DeveloperGuide.md
  docs/DevelopmentPractices.md
  docs/UserGuide.md
  logsstorage.log.lck
  src/main/java/seedu/notus/data/exception/SystemException.java
  src/main/java/seedu/notus/util/CommandMessage.java
  src/test/java/seedu/notus/command/ArchiveNoteCommandTest.java
  src/test/java/seedu/notus/command/ListNoteCommandTest.java
  src/test/java/seedu/notus/command/UnarchiveNoteCommandTest.java
  src/test/java/seedu/notus/util/parser/ParserManagerTest.java
Labels: priority.Medium, type.Task

#196 Documentation and bug fixes
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddNote_Sequence.puml
  docs/diagrams/Architecture_Overview.puml
  docs/diagrams/CommandClass.puml
  docs/diagrams/Formatter.puml
  docs/diagrams/InterfaceManagerClass.puml
  docs/diagrams/Notus.puml
  docs/diagrams/Parser.puml
  docs/diagrams/ParserManager.puml
  docs/diagrams/PinCommand.puml
  docs/diagrams/StorageManagerObject.puml
  docs/diagrams/out/AddNoteParser.png
  docs/diagrams/out/AddNote_Sequence.png
  docs/diagrams/out/Architecture_OverviewV2.png
  docs/diagrams/out/CommandClass.png
  docs/diagrams/out/Formatter.png
  docs/diagrams/out/InterfaceManagerClass.png
  docs/diagrams/out/Notus.png
  docs/diagrams/out/Parser.png
  docs/diagrams/out/ParserClasses.png
  docs/diagrams/out/ParserManagerClass.png
  docs/diagrams/out/PinCommand.png
  docs/diagrams/out/StorageManagerObject.png
  docs/screenshots/tagEvent.png
  logsstorage.log.lck
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/parser/ParseAddNoteCommand.java
  src/test/java/seedu/notus/util/parser/ParserManagerTest.java
Labels: type.Task

#200 Quick fix for edge case & issue from auto-merge
  src/main/java/seedu/notus/command/AddEventCommand.java
  src/main/java/seedu/notus/data/timetable/Event.java
Labels: severity.High, type.Bug

#204 save event tags
  src/main/java/seedu/notus/command/CreateTagCommand.java
  src/main/java/seedu/notus/command/TagEventCommand.java
  src/main/java/seedu/notus/command/TagNoteCommand.java
  src/main/java/seedu/notus/storage/StorageManager.java
  src/test/java/seedu/notus/command/CreateTagCommandTest.java
Labels: severity.Medium, type.Bug

#201 Update Docs & Add Test Cases
  docs/DevelopmentPractices.md
  docs/_config.yml
  docs/index.md
  docs/team/r-ramana.md
  src/main/java/seedu/notus/command/FindCommand.java
  src/main/java/seedu/notus/command/HelpCommand.java
  src/main/java/seedu/notus/util/parser/ParseArchiveOrUnarchiveNoteCommand.java
  src/test/java/seedu/notus/command/FindCommandStub.java
  src/test/java/seedu/notus/util/parser/ParseArchiveOrUnarchiveNoteCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseFindCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseListNoteCommandTest.java
Labels: priority.Medium, type.Task

#207 Prachi ppp
  docs/team/prachi2023.md
  src/main/java/seedu/notus/data/notebook/Note.java
Labels: priority.High, type.Task

#211 Fix the storage location of logging files for storage and help
  src/main/java/seedu/notus/command/HelpCommand.java
  src/main/java/seedu/notus/storage/StorageManager.java
Labels: priority.Medium, type.Bug

#209 Update PPP
  docs/_config.yml
  docs/team/r-ramana.md
Labels: priority.High

#202 Updated PPP and minor change to Developer Guide
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/Architecture_Overview.puml
  docs/diagrams/out/Architecture_OverviewV3.png
  docs/team/chongjx.md
  docs/team/junxiang.md
Labels: type.Task

#210 dev guide update storage
  docs/DeveloperGuide.md
  docs/diagrams/StorageManager.puml
  docs/diagrams/StorageManagerSaveDuring.puml
  docs/diagrams/out/StorageManager.png
  docs/diagrams/out/StorageManagerSaveDuring.png
  docs/diagrams/out/StorageManagerSaveEnd.png
  docs/diagrams/storageManagerSaveEnd.puml
Labels: priority.High, type.Task

#213 Prachi branch j unit test
  data/archived_notebook.txt
  src/test/java/seedu/notus/command/ArchiveNoteCommandTest.java
  src/test/java/seedu/notus/command/PinCommandTest.java
Labels: priority.Low, type.Task

#215 Prachi branch logging file save in folder bug
  logs/storage.log.1
  logs/storage.log.lck
  src/main/java/seedu/notus/storage/StorageManager.java
Labels: priority.Low, type.Bug

#216 unarchive notes junit test
  data/archived_notebook.txt
  src/main/java/seedu/notus/storage/StorageManager.java
  src/test/java/seedu/notus/command/ArchiveNoteCommandTest.java
  src/test/java/seedu/notus/command/UnarchiveNoteCommandTest.java
Labels: priority.Medium, type.Task

#217 Minor changes to the development practices doc
  docs/DevelopmentPractices.md
Labels: priority.Medium, type.Task

#218 Clean Up docs
  docs/AboutUs.md
  docs/DevelopmentPractices.md
  docs/diagrams/out/Gantt_Chart.png
  docs/team/brandonywl.md
  docs/team/chongjx.md
  docs/team/nazryl.md
  docs/team/prachi2023.md
  docs/team/r-ramana.md
Labels: priority.Medium

#219 Clean Up docs
  docs/team/chongjx.md
  docs/team/nazryl.md
  docs/team/r-ramana.md
Labels: priority.Medium

#222 Prachi branch ppp
  docs/diagrams/PinCommand.puml
  docs/diagrams/out/PinCommand.png
  docs/team/prachi2023.md
Labels: severity.VeryLow, type.Task

#225 Brandon branch update UG
  docs/UserGuide.md
Labels: severity.Medium, type.Bug

#227 Fixed Reposense header and variable name in Reminder
  src/main/java/seedu/notus/command/RemindCommand.java
  src/main/java/seedu/notus/data/timetable/Event.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/test/java/seedu/notus/command/RemindCommandTest.java
Labels: priority.Medium, type.Bug

#229 Bug fix for when edit note is not saved
  src/main/java/seedu/notus/command/EditNoteCommand.java
  src/main/java/seedu/notus/util/parser/ParseFindCommand.java
Labels: severity.High, type.Bug
