Repository AY2021S1-CS2113-T13-1/tp, pull requests merged in 2020-10, with the labels that each got.

#4 Update AboutUs
  docs/AboutUs.md
Labels: documentation

#10 Framework
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/ui/InterfaceManager.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: enhancement

#12 Update base code and added missing class ListEventCommand
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/util/Parser.java
Labels: bug

#29 Setup test classes for JUnit tests
  src/main/java/seedu/duke/util/Parser.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/ListEventCommandTest.java
  src/test/java/seedu/duke/command/ListNoteCommandTest.java
  src/test/java/seedu/duke/command/PinCommandTest.java
  src/test/java/seedu/duke/command/RemindCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
  src/test/java/seedu/duke/command/ViewNoteCommandTest.java
  src/test/java/seedu/duke/data/exception/SystemExceptionTest.java
  src/test/java/seedu/duke/data/notebook/NoteTest.java
  src/test/java/seedu/duke/data/notebook/NotebookTest.java
  src/test/java/seedu/duke/data/notebook/TagTest.java
  src/test/java/seedu/duke/data/timetable/EventTest.java
  src/test/java/seedu/duke/data/timetable/TimetableTest.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
  src/test/java/seedu/duke/ui/InterfaceManagerTest.java
  src/test/java/seedu/duke/util/DateTimeManagerTest.java
  src/test/java/seedu/duke/util/ParserTest.java
Labels: priority.High, type.Task

#31 Add notes
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/IncorrectCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
Labels: priority.High, type.Story

#32 Delete Notes
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
Labels: priority.High, type.Story

#34 Add Find Command Functionality
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/ui/InterfaceManager.java
  src/main/java/seedu/duke/util/Parser.java
Labels: priority.Medium, type.Story

#36 Prachi branch save note as text file
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.High, type.Story

#38 Add functionality for ListNodeCommand
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/main/java/seedu/duke/util/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#37 Supports creating and deleting of multiple tags within one user input
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/DeleteTagCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/main/java/seedu/duke/util/Parser.java
Labels: priority.High, type.Story

#39 Add JavaDocs
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/util/Parser.java
Labels: priority.Medium, type.Enhancement, type.Task

#40 Update on delete, add note and refactor codes
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/DeleteTagCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
  src/test/java/seedu/duke/command/AddNoteCommandTest.java
  src/test/java/seedu/duke/command/DeleteNoteCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Bug, type.Enhancement, type.Story

#44 Implemented Event Functionality
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
Labels: priority.High, type.Story

#46 Daily, Weekly, Monthly, Yearly Events
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/timetable/DailyEvent.java
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/MonthlyEvent.java
  src/main/java/seedu/duke/data/timetable/RecurringEvent.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/main/java/seedu/duke/data/timetable/WeeklyEvent.java
  src/main/java/seedu/duke/data/timetable/YearlyEvent.java
  src/main/java/seedu/duke/util/DateTimeManager.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.High, type.Story

#45 Add view note command
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/util/Parser.java
Labels: priority.High, type.Story

#47 Code Review for v0.1
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/DeleteTagCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/EditEventCommand.java
  src/main/java/seedu/duke/command/EditNoteCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/ListTagCommand.java
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/RemindCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/main/java/seedu/duke/ui/InterfaceManager.java
  src/main/java/seedu/duke/util/DateTimeManager.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
  src/test/java/seedu/duke/command/EditEventCommandTest.java
  src/test/java/seedu/duke/command/EditNoteCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#49 Prachi branch pin and unpin notes
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/util/Parser.java
Labels: type.Story

#57 Command classes now have an storageManager object to save notes and events accordingly.
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Command.java
Labels: priority.High, type.Task

#56 Minor refactor and comments on add and delete notes
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
Labels: priority.High, type.Enhancement, type.Story

#51 Clean ListCommand, HelpCommand and FindCommand
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/DeleteTagCommand.java
  src/main/java/seedu/duke/command/EditEventCommand.java
  src/main/java/seedu/duke/command/EditNoteCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/ListTagCommand.java
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/RemindCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/util/DateTimeManager.java
  src/main/java/seedu/duke/util/Parser.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: priority.High, type.Bug, type.Enhancement

#53 Minor edits and refactors done to code
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/notebook/Note.java
Labels: priority.Medium, type.Enhancement

#58 Changes from Code Review
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
Labels: priority.High, type.Enhancement, type.Task

#64 Junit AssertEquals Test for HelpCommand
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: priority.High, type.Enhancement

#52 Added Reminder functionality to events as well as fixed Recurrent Events
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/command/RemindCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/timetable/DailyEvent.java
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/MonthlyEvent.java
  src/main/java/seedu/duke/data/timetable/RecurringEvent.java
  src/main/java/seedu/duke/data/timetable/Reminder.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/main/java/seedu/duke/data/timetable/WeeklyEvent.java
  src/main/java/seedu/duke/data/timetable/YearlyEvent.java
  src/main/java/seedu/duke/util/DateTimeManager.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Story

#63 Implemented JUnit test for all Tag related features
  .gitignore
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/DeleteTagCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
  src/test/java/seedu/duke/command/CreateTagCommandTest.java
  src/test/java/seedu/duke/command/DeleteTagCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
  src/test/java/seedu/duke/data/notebook/TagManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Enhancement, type.Task

#67 Clean Duke code and add Test Case for FindCommand
  src/main/java/seedu/duke/Duke.java
  src/test/java/seedu/duke/command/FindCommandTest.java
Labels: priority.High, type.Enhancement

#66 Final clean up of code for v1.0
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/RemindCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/Reminder.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/main/java/seedu/duke/ui/InterfaceManager.java
  src/main/java/seedu/duke/util/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#74 Junit Delete, Add and deleteLine with v1.0
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/test/java/seedu/duke/command/AddNoteCommandTest.java
  src/test/java/seedu/duke/command/DeleteNoteCommandTest.java
  src/test/java/seedu/duke/util/ParserTest.java
Labels: priority.High, type.Task

#71 Prachi branch j unit test pin and view note command
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/test/java/seedu/duke/command/PinCommandTest.java
  src/test/java/seedu/duke/command/ViewNoteCommandTest.java
Labels: priority.High, type.Task

#55 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#65 Added JUnit Test for Event.
  build.gradle
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/Reminder.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/test/java/seedu/duke/command/AddEventCommandTest.java
  src/test/java/seedu/duke/command/RemindCommandTest.java
  src/test/java/seedu/duke/data/timetable/DailyEventTest.java
  src/test/java/seedu/duke/data/timetable/EventTest.java
  src/test/java/seedu/duke/data/timetable/MonthlyEventTest.java
  src/test/java/seedu/duke/data/timetable/TimetableTest.java
  src/test/java/seedu/duke/data/timetable/WeeklyEventTest.java
  src/test/java/seedu/duke/data/timetable/YearlyEventTest.java
Labels: type.Task

#78 List-n to display pinned and unpinned notes separately, catch null point exception for find-n
  FindCommand.log
  FindCommand.log.lck
  HelpCommand.log
  HelpCommand.log.1
  HelpCommand.log.1.lck
  HelpCommand.log.lck
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/util/Parser.java
Labels: priority.High, type.Bug, type.Enhancement, type.Story

#75 Temporary fix for printing color in windows command prompt
  FindCommand.log
  FindCommand.log.lck
  HelpCommand.log
  HelpCommand.log.lck
  build.gradle
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/RemindCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/RecurringEvent.java
  src/main/java/seedu/duke/ui/InterfaceManager.java
  src/main/java/seedu/duke/util/Formatter.java
  src/test/java/seedu/duke/command/CreateTagCommandTest.java
  src/test/java/seedu/duke/command/DeleteTagCommandTest.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/RemindCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
  src/test/java/seedu/duke/command/ViewNoteCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.Medium

#81 Update README.md
  README.md
Labels: priority.Low, type.Task

#80 Beautified Welcome Screen
  HelpCommand.log
  HelpCommand.log.1
  HelpCommand.log.1.lck
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low, type.Task

#82 Suggested fix for printing color fonts in Windows terminal
  FindCommand.log
  HelpCommand.log
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/test/java/seedu/duke/command/CreateTagCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.High, type.Bug

#84 Refactor code
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/RemindCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/RecurringEvent.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/test/java/seedu/duke/command/CreateTagCommandTest.java
  src/test/java/seedu/duke/command/DeleteTagCommandTest.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/RemindCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
  src/test/java/seedu/duke/command/ViewNoteCommandTest.java
Labels: priority.Medium, type.Task

#83 Update Formatter class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteTagCommand.java
  src/main/java/seedu/duke/command/ListTagCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/test/java/seedu/duke/command/CreateTagCommandTest.java
  src/test/java/seedu/duke/command/DeleteTagCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
  src/test/java/seedu/duke/data/notebook/TagManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#87 Added jansi library to allow printing of text font in windows terminal
  .gitignore
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/DeleteTagCommand.java
  src/main/java/seedu/duke/command/ListTagCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/test/java/seedu/duke/command/DeleteTagCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
Labels: severity.Low, type.Task

#90 Update ListNoteCommand test cases + UML diagram for dev guide + goodbye message ascii art
  .gitignore
  FindCommand.log
  FindCommandParser.log.1
  FindCommandParser.log.1.lck
  FindCommandParser.log.lck
  HelpCommand.log
  HelpCommand.log.1
  docs/diagrams/Architecture_Overview.puml
  docs/diagrams/Command.puml
  docs/diagrams/Style.puml
  docs/diagrams/out/Architecture_Overview.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/ui/AsciiArt.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/ListNoteCommandTest.java
  src/test/java/seedu/duke/ui/AsciiArtTest.java
  src/test/java/seedu/duke/ui/FormatterTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Low, type.Enhancement

#91 Modified Formatter encloseRow function to check for colored strings
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CreateTagCommand.java
  src/main/java/seedu/duke/command/EditEventCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: priority.High, type.Enhancement

#89 Update User Guide
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#101 Added assertion and logging for tag related functions
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/data/notebook/TagManager.java
Labels: priority.Medium, type.Task

#103 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#104 Update Developer Guide (Draft)
  docs/DeveloperGuide.md
  docs/diagrams/Notus.puml
  docs/diagrams/Parser.puml
Labels: priority.Medium, type.Task

#102 Archive Function
  .gitignore
  src/main/java/seedu/duke/command/ArchiveNoteCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/UnarchiveNoteCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
  src/test/java/seedu/duke/command/AddNoteCommandTest.java
  src/test/java/seedu/duke/command/DeleteNoteCommandTest.java
  src/test/java/seedu/duke/command/DeleteTagCommandTest.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/ListNoteCommandTest.java
  src/test/java/seedu/duke/command/PinCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
  src/test/java/seedu/duke/command/ViewNoteCommandTest.java
  src/test/java/seedu/duke/data/notebook/TagManagerTest.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.High, type.Story

#109 Sequence diagram for add note
  docs/diagrams/AddNote_Sequence.puml
Labels: priority.High, type.Task

#110 Exports for .puml image
  docs/diagrams/Command.puml
  docs/diagrams/out/AddNote_Sequence.png
  docs/diagrams/out/Notus.png
  docs/diagrams/out/Parser.png
Labels: priority.Medium

#111 Add notes improvements
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/main/java/seedu/duke/util/Parser.java
  src/test/java/seedu/duke/command/AddNoteCommandTest.java
  src/test/java/seedu/duke/command/DeleteNoteCommandTest.java
  src/test/java/seedu/duke/command/DeleteTagCommandTest.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/ListNoteCommandTest.java
  src/test/java/seedu/duke/command/PinCommandTest.java
  src/test/java/seedu/duke/command/TagCommandTest.java
  src/test/java/seedu/duke/command/ViewNoteCommandTest.java
  src/test/java/seedu/duke/data/notebook/TagManagerTest.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.High, type.Enhancement, type.Story

#108 Refactor add and delete events, and remind display.
  src/main/java/seedu/duke/command/AddEventCommand.java
  src/main/java/seedu/duke/command/DeleteEventCommand.java
  src/main/java/seedu/duke/command/RemindCommand.java
  src/main/java/seedu/duke/data/timetable/RecurringEvent.java
  src/main/java/seedu/duke/data/timetable/Reminder.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/test/java/seedu/duke/command/RemindCommandTest.java
Labels: priority.Medium

#112 Prachi branch pin and view note logging
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/ViewNoteCommand.java
Labels: priority.Medium, type.Task

#116 Update developer's guide on usage of color libraries
  docs/DeveloperGuide.md
  docs/diagrams/Notus.puml
  docs/diagrams/out/ConsoleColor.png
Labels: type.Task

#113 Fix Bugs, Update JavaDocs and Include PERT Chart
  docs/diagrams/PERT_Chart.puml
  docs/diagrams/out/PERT_Chart.png
  src/main/java/seedu/duke/command/ArchiveNoteCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/UnarchiveNoteCommand.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/util/Parser.java
Labels: priority.Medium, type.Task

#114 Add uml diagram for pin Command
  docs/DeveloperGuide.md
  docs/diagrams/PinCommand.puml
  docs/diagrams/out/PinCommand.png
Labels: priority.Medium, type.Task

#119 List-n/Archive-n bug fixes, documentation updates, clean code and updated test cases
  FindCommandParser.log.lck
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/PERT_Chart.puml
  docs/diagrams/Style.puml
  src/main/java/seedu/duke/command/ArchiveNoteCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListNoteCommand.java
  src/main/java/seedu/duke/command/UnarchiveNoteCommand.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/test/java/seedu/duke/command/ArchiveNoteCommandTest.java
  src/test/java/seedu/duke/command/FindCommandStub.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/ListNoteCommandTest.java
  src/test/java/seedu/duke/command/PinCommandTest.java
  src/test/java/seedu/duke/command/UnarchiveNoteCommandTest.java
  src/test/java/seedu/duke/data/notebook/NotebookStub.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
  src/test/java/seedu/duke/ui/FormatterStub.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Task

#107 Refactor list events formatting and fixed bug on list-n and list-e
  src/main/java/seedu/duke/command/ListEventCommand.java
  src/main/java/seedu/duke/data/timetable/Event.java
  src/main/java/seedu/duke/data/timetable/Timetable.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/main/java/seedu/duke/util/Parser.java
Labels: priority.Medium, type.Task

#120 Prachi branch save note as text file
  data/notebook.txt
  data/notes/bloop.txt
  data/tags.txt
  data/timetable.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/DeleteNoteCommand.java
  src/main/java/seedu/duke/command/PinCommand.java
  src/main/java/seedu/duke/command/TagCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/Tag.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/test/java/seedu/duke/command/DeleteNoteCommandTest.java
  src/test/java/seedu/duke/command/PinCommandTest.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.Medium, type.Story

#121 Edit notes
  src/main/java/seedu/duke/command/AddNoteCommand.java
  src/main/java/seedu/duke/command/EditNoteCommand.java
  src/main/java/seedu/duke/data/exception/SystemException.java
  src/main/java/seedu/duke/data/notebook/Note.java
  src/main/java/seedu/duke/data/notebook/Notebook.java
  src/main/java/seedu/duke/ui/Formatter.java
  src/main/java/seedu/duke/util/Parser.java
  src/main/java/seedu/duke/util/PrefixSyntax.java
  src/test/java/seedu/duke/command/AddNoteCommandTest.java
Labels: priority.Medium, type.Bug, type.Enhancement, type.Story

#125 Minor code clean up
  src/main/java/seedu/notus/command/DeleteNoteCommand.java
  src/main/java/seedu/notus/data/notebook/Note.java
  src/main/java/seedu/notus/data/notebook/Notebook.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/parser/Parser.java
  src/test/java/seedu/notus/util/parser/ParseCreateOrDeleteTagCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseTagCommandTest.java
  src/test/java/seedu/notus/util/parser/ParserTest.java
Labels: type.Task

#127 Update list-n display for pinned notes
  TagManager.log.2
  TagManager.log.2.lck
  data/notebook.txt
  data/notes/title 2.txt
  data/notes/title 3.txt
  data/notes/title 4.txt
  data/notes/title.txt
  src/main/java/seedu/notus/command/HelpCommand.java
  src/main/java/seedu/notus/command/ListNoteCommand.java
  src/main/java/seedu/notus/data/notebook/Notebook.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/test/java/seedu/notus/command/ListNoteCommandTest.java
Labels: priority.Medium, type.Enhancement

#126 Update developer's guide and uml diagram
  data/notebook.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddNote_Sequence.puml
  docs/diagrams/Architecture_Overview.puml
  docs/diagrams/Command.puml
  docs/diagrams/Notus.puml
  docs/diagrams/Parser.puml
  docs/diagrams/PinCommand.puml
  docs/diagrams/TaggableObject.puml
  docs/diagrams/out/AddNoteParser.png
  docs/diagrams/out/AddNote_Sequence.png
  docs/diagrams/out/Architecture_Overview.png
  docs/diagrams/out/Notus.png
  docs/diagrams/out/Parser.png
  docs/diagrams/out/PinCommand.png
  docs/diagrams/out/TaggableObject.png
  src/main/java/seedu/notus/Notus.java
Labels: priority.High, type.Task

#128 Add Notebook section in dev guide
  docs/DeveloperGuide.md
  docs/diagrams/NotebookObject.puml
  docs/diagrams/out/NotebookObject.png
  docs/diagrams/out/PERT_Chart.png
  src/main/java/seedu/notus/data/notebook/Notebook.java
  src/main/java/seedu/notus/util/parser/Parser.java
Labels: priority.High, type.Task

#122 Prachi branch save event as text file
  data/notebook.txt
  src/main/java/seedu/notus/Notus.java
  src/main/java/seedu/notus/command/AddEventCommand.java
  src/main/java/seedu/notus/command/ArchiveNoteCommand.java
  src/main/java/seedu/notus/command/DeleteEventCommand.java
  src/main/java/seedu/notus/command/DeleteNoteCommand.java
  src/main/java/seedu/notus/command/DeleteTagCommand.java
  src/main/java/seedu/notus/command/PinCommand.java
  src/main/java/seedu/notus/command/TagNoteCommand.java
  src/main/java/seedu/notus/command/UnarchiveNoteCommand.java
  src/main/java/seedu/notus/data/timetable/Event.java
  src/main/java/seedu/notus/data/timetable/RecurringEvent.java
  src/main/java/seedu/notus/data/timetable/Timetable.java
  src/main/java/seedu/notus/storage/StorageManager.java
  src/test/java/seedu/notus/command/AddEventCommandTest.java
  src/test/java/seedu/notus/command/AddNoteCommandTest.java
  src/test/java/seedu/notus/command/DeleteNoteCommandTest.java
Labels: priority.High, type.Story

#132 Update Notebook object
  docs/diagrams/NotebookObject.puml
  docs/diagrams/out/NotebookObject.png
Labels: priority.High, type.Task

#130 Update User Guide and Dev Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Architecture_Overview.puml
  docs/diagrams/Command.puml
  docs/diagrams/out/Architecture_Overview.png
  docs/diagrams/out/Command.png
Labels: priority.Medium, type.Task

#133 Update DG
  .gitignore
  data/notebook.txt
  data/timetable.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/Formatter.puml
  docs/diagrams/NotebookObject.puml
  docs/diagrams/ParserManager.puml
  docs/diagrams/SystemExceptionEnum.puml
  docs/diagrams/TaggableObject.puml
  docs/diagrams/out/Formatter.png
  docs/diagrams/out/NotebookObject.png
  docs/diagrams/out/ParserClasses.png
  docs/diagrams/out/ParserManagerClass.png
  docs/diagrams/out/SystemExceptionEnum1.png
  docs/diagrams/out/SystemExceptionEnum2.png
  docs/diagrams/out/TaggableObject.png
  docs/screenshots/addNote.PNG
  docs/screenshots/archiveNote.PNG
  docs/screenshots/createTag.PNG
  docs/screenshots/deleteNote.PNG
  docs/screenshots/deleteTag.PNG
  docs/screenshots/findNote.PNG
  docs/screenshots/help.PNG
  docs/screenshots/listNote.PNG
  docs/screenshots/listTag.PNG
  docs/screenshots/pinNote.PNG
  docs/screenshots/startUp.PNG
  docs/screenshots/tagAndUntag.PNG
  docs/screenshots/unarchiveNote.PNG
  docs/screenshots/viewNote.PNG
  src/main/java/seedu/notus/Notus.java
  src/main/java/seedu/notus/command/FindCommand.java
  src/main/java/seedu/notus/command/HelpCommand.java
  src/main/java/seedu/notus/command/ListNoteCommand.java
  src/main/java/seedu/notus/data/notebook/Notebook.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/parser/ParseCreateOrDeleteTagCommand.java
  src/main/java/seedu/notus/util/parser/Parser.java
  src/main/java/seedu/notus/util/parser/ParserManager.java
  src/test/java/seedu/notus/command/FindCommandTest.java
  src/test/java/seedu/notus/command/HelpCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseAddEventCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseAddNoteCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseArchiveOrUnarchiveNoteCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseCreateOrDeleteTagCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseDeleteEventCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseDeleteNoteCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseEditEventCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseEditNoteCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseFindCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseListEventCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseListNoteCommandTest.java
  src/test/java/seedu/notus/util/parser/ParsePinCommandTest.java
  src/test/java/seedu/notus/util/parser/ParseViewNoteCommandTest.java
Labels: priority.Medium, type.Task

#137 Revert changes and update png file names
  docs/UserGuide.md
  docs/screenshots/addNote.png
  docs/screenshots/archiveNote.png
  docs/screenshots/createTag.png
  docs/screenshots/deleteNote.png
  docs/screenshots/deleteTag.png
  docs/screenshots/findNote.png
  docs/screenshots/help.png
  docs/screenshots/listNote.png
  docs/screenshots/listTag.png
  docs/screenshots/pinNote.png
  docs/screenshots/startUp.png
  docs/screenshots/tagAndUntag.png
  docs/screenshots/unarchiveNote.png
  docs/screenshots/viewNote.png
  src/main/java/seedu/notus/command/HelpCommand.java
  src/test/java/seedu/notus/command/HelpCommandTest.java
Labels: severity.VeryLow

#136 Added edit events support
  data/notes/C++ Standard Libraries.txt
  data/notes/Java OOP.txt
  data/notes/test 2.txt
  data/notes/test1.txt
  src/main/java/seedu/notus/command/EditEventCommand.java
  src/main/java/seedu/notus/data/exception/SystemException.java
  src/main/java/seedu/notus/data/timetable/DailyEvent.java
  src/main/java/seedu/notus/data/timetable/Event.java
  src/main/java/seedu/notus/data/timetable/MonthlyEvent.java
  src/main/java/seedu/notus/data/timetable/RecurringEvent.java
  src/main/java/seedu/notus/data/timetable/Timetable.java
  src/main/java/seedu/notus/data/timetable/WeeklyEvent.java
  src/main/java/seedu/notus/data/timetable/YearlyEvent.java
  src/main/java/seedu/notus/storage/StorageManager.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/PrefixSyntax.java
  src/main/java/seedu/notus/util/parser/ParseAddEventCommand.java
  src/main/java/seedu/notus/util/parser/ParseEditEventCommand.java
  src/main/java/seedu/notus/util/parser/Parser.java
  src/test/java/seedu/notus/command/AddEventCommandTest.java
  src/test/java/seedu/notus/command/RemindCommandTest.java
  src/test/java/seedu/notus/data/timetable/DailyEventTest.java
  src/test/java/seedu/notus/data/timetable/EventTest.java
  src/test/java/seedu/notus/data/timetable/MonthlyEventTest.java
  src/test/java/seedu/notus/data/timetable/TimetableTest.java
  src/test/java/seedu/notus/data/timetable/WeeklyEventTest.java
  src/test/java/seedu/notus/data/timetable/YearlyEventTest.java
Labels: priority.High, type.Story

#138 Update the FAQ part of the ug
  docs/UserGuide.md
Labels: severity.VeryLow

#140 Updated user guide for event commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/screenshots/addEvent.png
  docs/screenshots/deleteEvent.png
  docs/screenshots/editEvent.png
  docs/screenshots/listEvent.png
  docs/screenshots/remindEvent.png
  src/main/java/seedu/notus/ui/Formatter.java
Labels: priority.High, type.Task

#141 Update UG on Edit note
  docs/UserGuide.md
  docs/diagrams/NotebookObject.puml
  docs/diagrams/out/NotebookObject.png
  docs/screenshots/editNote.png
  src/main/java/seedu/notus/command/EditNoteCommand.java
Labels: priority.High, type.Task

#143 Refactor Code
  src/main/java/seedu/notus/command/AddEventCommand.java
  src/main/java/seedu/notus/command/AddNoteCommand.java
  src/main/java/seedu/notus/command/ArchiveNoteCommand.java
  src/main/java/seedu/notus/command/Command.java
  src/main/java/seedu/notus/command/CreateTagCommand.java
  src/main/java/seedu/notus/command/DeleteEventCommand.java
  src/main/java/seedu/notus/command/DeleteNoteCommand.java
  src/main/java/seedu/notus/command/DeleteTagCommand.java
  src/main/java/seedu/notus/command/EditEventCommand.java
  src/main/java/seedu/notus/command/EditNoteCommand.java
  src/main/java/seedu/notus/command/ExitCommand.java
  src/main/java/seedu/notus/command/FindCommand.java
  src/main/java/seedu/notus/command/HelpCommand.java
  src/main/java/seedu/notus/command/ListEventCommand.java
  src/main/java/seedu/notus/command/ListNoteCommand.java
  src/main/java/seedu/notus/command/ListTagCommand.java
  src/main/java/seedu/notus/command/PinCommand.java
  src/main/java/seedu/notus/command/RemindCommand.java
  src/main/java/seedu/notus/command/TagEventCommand.java
  src/main/java/seedu/notus/command/TagNoteCommand.java
  src/main/java/seedu/notus/command/UnarchiveNoteCommand.java
  src/main/java/seedu/notus/command/ViewNoteCommand.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/CommandMessage.java
  src/test/java/seedu/notus/command/AddNoteCommandTest.java
  src/test/java/seedu/notus/command/ArchiveNoteCommandTest.java
  src/test/java/seedu/notus/command/DeleteTagCommandTest.java
  src/test/java/seedu/notus/command/FindCommandTest.java
  src/test/java/seedu/notus/command/HelpCommandTest.java
  src/test/java/seedu/notus/command/PinCommandTest.java
  src/test/java/seedu/notus/command/RemindCommandTest.java
  src/test/java/seedu/notus/command/TagNoteCommandTest.java
  src/test/java/seedu/notus/command/UnarchiveNoteCommandTest.java
  src/test/java/seedu/notus/command/ViewNoteCommandTest.java
Labels: priority.Medium, type.Bug, type.Enhancement, type.Task

#144 Update UG and minor bug fixes
  docs/UserGuide.md
  docs/screenshots/createTag.png
  docs/screenshots/tagEvent.PNG
  docs/screenshots/tagNote.png
  src/main/java/seedu/notus/command/AddNoteCommand.java
  src/main/java/seedu/notus/command/IncorrectCommand.java
  src/main/java/seedu/notus/data/notebook/Notebook.java
  src/main/java/seedu/notus/ui/Formatter.java
  src/main/java/seedu/notus/util/parser/ParseDeleteEventCommand.java
  src/main/java/seedu/notus/util/parser/ParseEditNoteCommand.java
  src/main/java/seedu/notus/util/parser/Parser.java
Labels: severity.Low, type.Bug, type.Task

#142 Added display of all reminders of each event
  docs/UserGuide.md
  src/main/java/seedu/notus/ui/Formatter.java
Labels: priority.High, type.Enhancement

#170 Address archive-n /t issue
  src/main/java/seedu/notus/data/notebook/Notebook.java
Labels: severity.Medium, type.Bug
